name: CI

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '22 2 * * 0'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PACKER_VERSION: '1.5.6'
      AWS_DEFAULT_REGION: 'us-east-1'
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: pip install --upgrade aws-amicleaner
    - name: Install Packer
      run: |
            wget -q "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
            wget -qO - "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_SHA256SUMS" | grep linux_amd64 | sha256sum -c
            sudo unzip -o -d /usr/local/bin/ "packer_${PACKER_VERSION}_linux_amd64.zip"
            packer version
    - name: Validate AMI
      run: packer validate ami.json
    - name: Build AMI
      run: packer build ami.json
    - name: Clean AMIs
      run: amicleaner --mapping-key name --mapping-values 'Vault' --force-delete --full-report --keep-previous 1 --check-orphans
